---
title: "MPM 207: Applied Epidemiology Problem Solving"
output:
  html_document: 
    toc: true
    toc_float: true
editor_options: 
  markdown: 
    wrap: 72
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(kableExtra); library(dplyr)
knitr::opts_chunk$set(echo = F)
```

# COURSE OBJECTIVES:
By the end of the course, participants should be able to:
  
  1. Identify the different sources and nature of epidemiological data and understand their respective advantages and limitations.
  2. Conduct advanced data validation and manipulation and properly describe, represent, and analyze different types of epidemiologic information.
  3. Select the right analytical method depending on the research question to be addressed under different data formats and study designs.
  4. Calculate and understand the risk measures in different types of studies and how to deal with confounders or effect modifiers.
  5.  Perform simple and advanced statistical and epidemiological analyses with R-language.

# COURSE FORMAT:
The class will meet Thursdays, from 1:10-4:00 pm in 2020 Valley Hall. The course will consist of lecture/laboratories or discussion/laboratory sessions in which epidemiologic problems will be analyzed and discussed by the student. Please install the necessary software and use your own laptop for each session; you will need it for the labs. Guidelines, lectures, and other documentation to assist you in the lab will be provided in the course website:
 https://canvas.ucdavis.edu/courses/848091   

# COURSE GRADING:
The laboratory assignment constitutes 90% of the final grade. There will be no examinations. The remaining 10% of the grade is based on participation during the in-class activities and discussions. Course grading is noncompetitive; course grades will be assigned based on mastery of the material. We expect that students who have an average score of 90 or greater will receive an A- or A, and those with an average score of 80-90 will receive B-, B, or B+. Students who do not demonstrate mastery of the material will receive a grade of C or below. Lab assignments should be sent to the instructors using CANVAS or, if CANVAS fails or is not available, by email before the due day/time. Late assignments will be penalized with a lower score (they will lose 20% of their value for each day beyond the due day/time). There will be no option for resubmissions or make-ups of laboratory assignments after the due day/time.  
